### ISSUE TITLE
Validation failure on update does not route to error view

### ISSUE THREAD

**Issue by bgiromini** [NetCoreApps/Validation#1]
Steps to reproduce:

1. Create contact
2. Edit contact, remove a required value, like name
3. Click Update Contact Button

Result:

`Response Status
Error CodeNullReferenceExceptionMessageObject reference not set to an instance of an object.Stack Trace[UpdateContact: 09/29/2019 03:37:55]: [REQUEST: {id:1,title:Mrs,name:Rebekah,color:#b2fab4,filmGenres:[Action,Adventure,Drama],age:0,continue:/server-razor/contacts/,errorView:/server-razor/contacts/1/edit}] System.NullReferenceException: Object reference not set to an instance of an object. at ServiceStack.Mvc.RazorFormat.FindView(IEnumerable`1 viewNames, Dictionary`2& routingArgs) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack.Mvc\RazorFormat.cs:line 357 at ServiceStack.Mvc.RazorFormat.ProcessRequestAsync(IRequest req, Object dto, Stream outputStream) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack.Mvc\RazorFormat.cs:line 314 at ServiceStack.Formats.HtmlFormat.SerializeToStreamAsync(IRequest req, Object response, Stream outputStream) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack\Formats\HtmlFormat.cs:line 59Errors`

I am experiencing this same issue in my code and was reviewing this demo application to determine what I was doing wrong.

**Comment by mythz** [comment]
I can't repro this with those steps

![server-razor-repro](https://user-images.githubusercontent.com/89361/65832547-42c83e00-e293-11e9-9926-2a54ebf1c12b.gif)

**Comment by bgiromini** [comment]
I made sure to install the most recent release of netCore3 before doing this test.

1. Download code from github
2. Open Rider and press debug
3. Create and edit the contact, reproduce error.
4. Repeat steps on VS for Mac, get the same results
5. Tested in VS Code as well, got the same result

![2019-09-29_09-36-48 (1)](https://user-images.githubusercontent.com/5099290/65834070-d8b49680-e29c-11e9-9699-713ff09b806a.gif)

**Comment by mythz** [comment]
I'm doing exactly that but can't repro the issue. I've even tried running this from a different machine (macOS) from the command-line (`dotnet run`) but still works as expected. Can you try clearing out your NuGet packages cache?
https://docs.servicestack.net/myget#redownloading-myget-packages

I can't see the URLs in your animated gif, but from the stack trace I'm assuming you're testing server-razor version right?

**Comment by bgiromini** [comment]
Once again you are correct. Clearing the Nuget cache fixed the issue in this project and my personal project. That has bitten me quite a few times, so I should do it every time I upgrade my packages.

**Comment by mythz** [comment]
You should definitely try downloading the latest pre-release packages after running into any issues when using the pre-release packages. 

But if you don’t run into any issues there’s no need to make sure you’re using the latest.
